### ISSUE TITLE
More code examples, functionality

### ISSUE THREAD

**Issue by mallen012** [CyanLabs/ESP-MQTT-JSON-Digital-LEDs#10]
Hello, thanks again for all of the help. My lights are up and running perfectly. Have you seen this website or looked into expanding to some more lighting effects? http://frederickvandenbosch.be/?p=267

Here is one of the examples, how could I implement it into my config:

// Light up the strip starting from the middle
void middleFill(uint32_t c, uint8_t wait) {
  clearStrip();
 
  for(uint16_t i=0; i<(dstrip.numPixels()/2); i++) { // start from the middle, lighting an LED on each side
    dstrip.setPixelColor(dstrip.numPixels()/2 + i, c);
    dstrip.setPixelColor(dstrip.numPixels()/2 - i, c);
    dstrip.show();
    delay(wait);
  }
 
  for(uint16_t i=0; i<(dstrip.numPixels()/2); i++) { // reverse
    dstrip.setPixelColor(i, dstrip.Color(0, 0, 0));
    dstrip.setPixelColor(dstrip.numPixels() - i, dstrip.Color(0, 0, 0));
    dstrip.show();
    delay(wait);
  }
}

**Comment by fma965** [comment]
Feel free to implement the code however i won't be. Thanks
