### ISSUE TITLE
MQTT connection problem

### ISSUE THREAD

**Issue by KoumaMisna** [CyanLabs/ESP-MQTT-JSON-Digital-LEDs#11]
I have the same problem with this code as with the original one with Bruh. Continuous MQTT reconnects.

Here is the serial monitor:
`.........
WiFi connected
IP address: 192.168.5.112
Ready
Attempting MQTT connection...connected
Setting LEDs:
r: 0, g: 0, b: 0
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-4 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-4 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-4 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
`

And here is mosquitto log:
`1550323869: New client connected from 192.168.5.112 as tupa_allasvalo (c1, k15, u'mqttclients').
1550323890: Client tupa_allasvalo has exceeded timeout, disconnecting.
1550323890: Socket error on client tupa_allasvalo, disconnecting.`

**Comment by fma965** [comment]
I also had this problem, make sure you aint using the beta version of the board so im using esp8266 2.4.2 not the beta.

**Comment by KoumaMisna** [comment]
Sorry this was a faulty board. It kept disconnecting Wifi all the time. Now it's working perfect. Btw in the homeassistant example there is effect "sinelon" twice.

Another problem I have is how do I get the effect speed adjusted as Bruh did in his video?

**Comment by KoumaMisna** [comment]
Changed to board manager 2.4.2 from 2.5.0 and now also the other boards work. Great! Thanks for the advice.

**Comment by fma965** [comment]
it took me for ever to figure out the issue, and please read the readme.md to see how to use effect speed

**Comment by fma965** [comment]
basically its using the white value slider to control animation speed
