### ISSUE TITLE
exit status 1 Error compiling for board NodeMCU 1.0 (ESP-12E Module).

### ISSUE THREAD

**Issue by KodiMkd** [CyanLabs/ESP-MQTT-JSON-Digital-LEDs#12]
forget that..i downloaded the code but there is no way to configure yaml file for home assistant

**Comment by KodiMkd** [comment]
(MainThread) [homeassistant.components.homeassistant] Invalid config for [light.mqtt]: [flash] is an invalid option for [light.mqtt]. Check: light.mqtt->flash. (See ?, line ?). Please check the docs at https://home-assistant.io/components/light.mqtt/


anyone help with this ?? This is the code im using..just changing the mqtt info with mine.

mqtt:
  broker: your.mqtt.ip.address
  port: 1883
  client_id: home-assistant-1
  username: YOURUSERNAME
  password: YOURPASSWORD

light:
  - platform: mqtt
    schema: json
    name: "RGB Light Strip 1"
    state_topic: "home/RGBStrip1"
    command_topic: "home/RGBStrip1/set"
	availability_topic: "home/RGBStrip1/LWT"
    white_value: true
    effect: true
    effect_list:
      - solid    
      - Music - L2R
      - Music - Middle
      - Music - LR2M
      - Music - Fma965
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple  
      - sinelon    
      - twinkle
      - sinelon
      - sine hue
      - full hue
      - breathe
      - hue breathe
      - Christmas
      - christmas alternate
      - random stars
      - St Patty
      - Valentine
      - Turkey Day
      - Thanksgiving
      - USA
      - Independence
      - Halloween
      - Go Lions
      - Hail
      - Touchdown
      - Punkin
      - Lovey Day
      - Holly Jolly      
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

**Comment by fma965** [comment]
seems like you are on a old version of HA, what version are you on?

**Comment by fma965** [comment]
just remove 
flash: true
rgb: true

**Comment by fma965** [comment]
updated the config example. removing flash and rgb

**Comment by KodiMkd** [comment]
copied the updated code...still nothing..same thing

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
mqtt:
  broker: your.mqtt.ip.address
  port: 1883
  client_id: home-assistant-1
  username: YOURUSERNAME
  password: YOURPASSWORD

light:
    - platform: mqtt
    schema: json
    name: "RGB Light Strip 1"
    state_topic: "home/RGBStrip1"
    command_topic: "home/RGBStrip1/set"
    rgb: true
    availability_topic: "home/RGBStrip1/LWT"
    white_value: true
    effect: true
    effect_list:
      - solid    
      - Music - L2R
      - Music - Middle
      - Music - Fma965
      - bpm
      - candy cane  
      - confetti  
      - cyclon rainbow  
      - dots  
      - fire  
      - glitter  
      - juggle  
      - lightning
      - noise  
      - police all  
      - police one  
      - rainbow  
      - rainbow with glitter  
      - ripple      
      - twinkle
      - sinelon
      - sine hue
      - full hue
      - breathe
      - hue breathe
      - Christmas
      - christmas alternate
      - random stars
      - St Patty
      - Valentine
      - Turkey Day
      - Thanksgiving
      - USA
      - Independence
      - Halloween
      - Go Lions
      - Hail
      - Touchdown
      - Punkin
      - Lovey Day
      - Holly Jolly      
    brightness: true
    optimistic: false
    qos: 0


**and this are  the errors:**


2019-08-20 16:16:40 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] while parsing a block collection
  in "C:\Users\olire\AppData\Roaming\.homeassistant\configuration.yaml", line 24, column 5
expected <block end>, but found '?'
  in "C:\Users\olire\AppData\Roaming\.homeassistant\configuration.yaml", line 25, column 5
2019-08-20 16:16:40 ERROR (MainThread) [homeassistant.bootstrap] Error loading C:\Users\olire\AppData\Roaming\.homeassistant\configuration.yaml: while parsing a block collection
  in "C:\Users\olire\AppData\Roaming\.homeassistant\configuration.yaml", line 24, column 5
expected <block end>, but found '?'
  in "C:\Users\olire\AppData\Roaming\.homeassistant\configuration.yaml", line 25, column 5

**Comment by KodiMkd** [comment]
> 
> 
> seems like you are on a old version of HA, what version are you on?

newest   0.97.2
python 3.7
