### ISSUE TITLE
just no clue wtf is wrong

### ISSUE THREAD

**Issue by KodiMkd** [CyanLabs/ESP-MQTT-JSON-Digital-LEDs#13]
copied the updated code...still nothing..same thing..doesn't work
im on HA 0.97.2
python 3.7

Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
base_url: example.duckdns.org:8123
Text to speech

tts:

    platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
mqtt:
broker: your.mqtt.ip.address
port: 1883
client_id: home-assistant-1
username: YOURUSERNAME
password: YOURPASSWORD

light:
- platform: mqtt
schema: json
name: "RGB Light Strip 1"
state_topic: "home/RGBStrip1"
command_topic: "home/RGBStrip1/set"
rgb: true
availability_topic: "home/RGBStrip1/LWT"
white_value: true
effect: true
effect_list:
- solid
- Music - L2R
- Music - Middle
- Music - Fma965
- bpm
- candy cane
- confetti
- cyclon rainbow
- dots
- fire
- glitter
- juggle
- lightning
- noise
- police all
- police one
- rainbow
- rainbow with glitter
- ripple
- twinkle
- sinelon
- sine hue
- full hue
- breathe
- hue breathe
- Christmas
- christmas alternate
- random stars
- St Patty
- Valentine
- Turkey Day
- Thanksgiving
- USA
- Independence
- Halloween
- Go Lions
- Hail
- Touchdown
- Punkin
- Lovey Day
- Holly Jolly
brightness: true
optimistic: false
qos: 0

and this are the errors:

2019-08-20 16:16:40 ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] while parsing a block collection
in "C:\Users\olire\AppData\Roaming.homeassistant\configuration.yaml", line 24, column 5
expected , but found '?'
in "C:\Users\olire\AppData\Roaming.homeassistant\configuration.yaml", line 25, column 5
2019-08-20 16:16:40 ERROR (MainThread) [homeassistant.bootstrap] Error loading C:\Users\olire\AppData\Roaming.homeassistant\configuration.yaml: while parsing a block collection
in "C:\Users\olire\AppData\Roaming.homeassistant\configuration.yaml", line 24, column 5
expected , but found '?'
in "C:\Users\olire\AppData\Roaming.homeassistant\configuration.yaml", line 25, column 5
newest 0.97.2
python 3.7

**Comment by fma965** [comment]
yaml is very specific with tabbing / white space, make sure it's tabbed and spaced correctly at line 24 and 25

EDIT: without a properly formatted config i can't even see whats wrong, please either use code tags or paste it somewhere which doesn't format it (pastebin etc)

**Comment by fma965** [comment]
With all due respect this isn't an issue with my code, this is an issue with your configuration, i am using the code perfectly fine. please do not raise another issue unless you are 100% sure it's not your tabbing/indenting thats the issue.

**Comment by KodiMkd** [comment]
> 
> 
> With all due respect this isn't an issue with my code, this is an issue with your configuration, i am using the code perfectly fine. please do not raise another issue unless you are 100% sure it's not your tabbing/indenting thats the issue.

i apologize for that because im not literate for yaml files,any of the programming actually in general.

**Comment by fma965** [comment]
Please run the config through a yaml validator http://www.yamllint.com/ for example
