### ISSUE TITLE
parseObject() failed

### ISSUE THREAD

**Issue by marrobHD** [CyanLabs/ESP-MQTT-JSON-Digital-LEDs#2]
Attempting MQTT connection...connected
Setting LEDs:
r: 0, g: 0, b: 0
Message arrived [home/RGBStrip1/set] ON
parseObject() failed

**Comment by fma965** [comment]
that seems like whatever you are sending to it isnt correctly formatted.

**Comment by marrobHD** [comment]
HomeAssistant sending the code. It used to work, today I wanted to test it again and it does not work anymore. How shows a right formatted message

**Comment by fma965** [comment]
no idea then, i've only ever had this issue when my json was invalid.

**Comment by marrobHD** [comment]
All is working now please close.
