### ISSUE TITLE
How work the Music Virtualizer

### ISSUE THREAD

**Issue by marrobHD** [CyanLabs/ESP-MQTT-JSON-Digital-LEDs#3]
How work the Music Virtualizer.
Which Things I have to connect to the NodeMCU board?

**Comment by fma965** [comment]
please read the readme on the home page of this github repo

**Comment by fma965** [comment]
Music Visualizer
This requires some sort of sound device, Microphone or a speaker output from an amp. for my purposes i spliced in to the speaker output of a rear speaker and connected 1 end to my amp and the other to the NodeMCU. The pins that are used for this code are A0 for the possitive (red speaker wire) and GND for the GND (black speaker wire). This works perfectly without requiring any extra hardware. it also doesn't get ruined by voice as it's using a direct sound output.

Some of the effects incorporate the currrently selected color (sinelon, confetti, juggle, etc) while other effects use pre-defined colors. You can also select custom transition speeds between colors. The transition variable in Home Assistant (HA) also functions to control the animation speed of the currently running animation. The input_slider and automation in the HA configuration example allow you to easily set a transition speed from HA's user interface without needing to use the Services tool.

The default speed for the effects is hard coded and is set when the light is first turned on. When changing between effects, the previously used transition speed will take over. If the effects don't look great, play around with the slider to adjust the transition speed (AKA the effect's animation speed).
