### ISSUE TITLE
Animation Freezes upon internet/wifi disconnection

### ISSUE THREAD

**Issue by insane2subro** [CyanLabs/ESP-MQTT-JSON-Digital-LEDs#4]
My problem is when ever the wifi/internet disconnects the animation freezes only to resume after the wifi/internet is back.

In India where data disconnection is very frequent with all ISPs it is a big problem, is there any way out of this?

**Comment by fma965** [comment]
Why would you have it connected via the internet use a local area network
(LAN)

**Comment by deysubro** [comment]
Well I wanted this to work on an online broker.. Can this be done? It works like a charm I just wanted the animation to not freeze when ever a wifi disconnection happens. 

P.S Thankyou for such prompt reply

**Comment by fma965** [comment]
No idea, i personally use a local MQTT broker. sorry.

**Comment by deysubro** [comment]
No worries! Its a Hardware interrupt I believe! Also Can you suggest a way where I could save the last state so upon restart the last state is loaded.

**Comment by fma965** [comment]
I really wouldn't know, i haven't had a massive amount of experience with
Arduino like devices (nodeMCU etc) i just merged a bunch of code and added
a few effects for my specific use case.

**Comment by deysubro** [comment]
Ok Thanks a lot anyway :)
