### ISSUE TITLE
Wiring on my end, just not right...

### ISSUE THREAD

**Issue by mallen012** [CyanLabs/ESP-MQTT-JSON-Digital-LEDs#5]
Hello, I have tried for 2 days to get this hooked up and am so close. I have the upload and connection working from Arduino IDE, and can see the unit on my network and toggle switches from Hassio and see my switching across the serial monitor, just can’t get the LED strips to power up or respond. I am using the ones below. 

https://www.amazon.com/gp/product/B01CNL6MNM/ref=ppx_od_dt_b_asin_title_o00_s01?ie=UTF8&psc=1

Any ideas? I’m guessing it can be something with my wiring. 

Thanks in advance, Mike

**Comment by fma965** [comment]
Please post details photos showing your wiring.

**Comment by fma965** [comment]
you need to power the 12v strip with a 12v supply, gnd and +12v, then the middle pin (data pin) needs to go to pin D3 on the nodemcu, unless you change the code to use another pin, also keep in mind that if you have a long distance from your first LED and the node mcu, you will need a logic level shifter, i don't use one as my first LED is only about 50cm from the NodeMCU

**Comment by mallen012** [comment]
That was it, I was reading the diagram and connecting to D5. All working now.

**Comment by fma965** [comment]
i changed it to D3 for my own reasons, i should update the image.
