### ISSUE TITLE
Animation Speed, slider and switch

### ISSUE THREAD

**Issue by mallen012** [CyanLabs/ESP-MQTT-JSON-Digital-LEDs#6]
I also originally deployed the following code and it shows up on my Overview page, but does not control my strip. Any ideas if it should still work?

I know input_slider is now changed to input_number, and a few more changes I made below. Do the new changes effect it as well? Any help would be appreciated.

input_number:
  led_animation_speed:
    name: RGB Light Strip 1
    initial: 150
    min: 1
    max: 150
    step: 10

Animations.yaml

id: "Led Strip Animation Speed"
hide_entity: False
initial_state: True
trigger:
    - platform: state
      entity_id: input_number.led_animation_speed
action:
    - service: mqtt.publish
      data_template:
        topic: "home/RGBStrip1/set"
        payload: '{"transition":{{ trigger.to_state.state | int }}}'

**Comment by fma965** [comment]
You dont need any of that in my code, you can adjust the white value and it
will control animation speed.

**Comment by mallen012** [comment]
Dude! This is super cool, any other tweaks your looking to beta or test in the future?

**Comment by fma965** [comment]
Not sure either now but bruhautomation is back
