### ISSUE TITLE
Convert to cpp files then split file

### ISSUE THREAD

**Issue by ljmerza** [CyanLabs/ESP-MQTT-JSON-Digital-LEDs#7]
Thank you for this project! You've taken it way further than the original. I was wondering if it's possible for you to convert this to cpp/h files? Not everyone uses the Arduino IDE but with cpp/h files you can use these on any IDE including Arduino. This would also help with splitting this monster of a file up so it can be maintained easier for everyone. I can help with this if you are interested. Thanks!

**Comment by fma965** [comment]
Happy to accept PR's but not something i will be doing my self.
